site_name: Awesome オープンコンタクト JP
nav:
  - ホーム: index.md
  - 支援者の方へ: contributor.md
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
  font:
    text: Mochiy Pop One
  language: ja
  logo: assets/akusyu_uchuujin.png
  favicon: assets/akusyu_uchuujin.png
extra_css:
  - style/extra.css
markdown_extensions:
  - attr_list
  - pymdownx.details

